[http]
	extraHeader = X-Gitaly-Correlation-ID: 9c174f30a15b74d8-IAD
[transfer]
	bundleURI = true
[http "https://gitlab.com"]
	sslCAInfo = /home/mid-project-vote-app/builds/ldx0lvsbv/0/mennakhalil/mid-project-vote-app.tmp/CI_SERVER_TLS_CA_FILE
[url "https://gitlab-ci-token:glcbt-6b_-aTxn5H_poxahbxMxTdn@gitlab.com/mennakhalil/mid-project-vote-app.git"]
	insteadOf = https://gitlab.com/mennakhalil/mid-project-vote-app.git
[url "https://gitlab-ci-token:glcbt-6b_-aTxn5H_poxahbxMxTdn@gitlab.com"]
	insteadOf = https://gitlab.com
